// Code generated by mcpidl. DO NOT EDIT.

package main

type GetVolumeInput struct {
	StreamType string `json:"streamType" jsonschema:"Stream type: music, ring, alarm, notification, system, voice_call"`
}

type GetVolumeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SetVolumeInput struct {
	StreamType string `json:"streamType" jsonschema:"Stream type"`
	Volume     int64  `json:"volume" jsonschema:"Volume level"`
}

type SetVolumeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetRingerModeInput struct {
}

type GetRingerModeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SetRingerModeInput struct {
	Mode string `json:"mode" jsonschema:"Ringer mode: normal, silent, vibrate"`
}

type SetRingerModeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type IsMusicActiveInput struct {
}

type IsMusicActiveOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetAudioSystemInfoInput struct {
}

type GetAudioSystemInfoOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
