// Code generated by mcpidl. DO NOT EDIT.

package main

type IsBluetoothEnabledInput struct {
}

type IsBluetoothEnabledOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SetBluetoothEnabledInput struct {
	Enabled bool `json:"enabled" jsonschema:"Whether to enable Bluetooth"`
}

type SetBluetoothEnabledOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetPairedDevicesInput struct {
}

type GetPairedDevicesOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type StartDiscoveryInput struct {
}

type StartDiscoveryOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type CancelDiscoveryInput struct {
}

type CancelDiscoveryOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
