// Code generated by mcpidl. DO NOT EDIT.

package main

type GetAllCalendarsInput struct {
}

type GetAllCalendarsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetPrimaryCalendarIdInput struct {
}

type GetPrimaryCalendarIdOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetAllEventsInput struct {
	Limit *int64 `json:"limit" jsonschema:"Maximum number of events to retrieve (default 20)"`
}

type GetAllEventsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetEventCountInput struct {
}

type GetEventCountOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type CreateEventInput struct {
	EndTime    int64   `json:"endTime" jsonschema:"End time in milliseconds since epoch"`
	Location   *string `json:"location" jsonschema:"Event location"`
	StartTime  int64   `json:"startTime" jsonschema:"Start time in milliseconds since epoch"`
	Title      string  `json:"title" jsonschema:"Event title"`
	CalendarId *int64  `json:"calendarId" jsonschema:"Calendar ID (optional)"`
}

type CreateEventOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type DeleteEventInput struct {
	EventId int64 `json:"eventId" jsonschema:"Event ID to delete"`
}

type DeleteEventOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SearchEventsInput struct {
	Keyword string `json:"keyword" jsonschema:"Search keyword"`
	Limit   *int64 `json:"limit" jsonschema:"Maximum number of results"`
}

type SearchEventsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetUpcomingEventsInput struct {
	Days  *int64 `json:"days" jsonschema:"Number of days to look ahead (default 7)"`
	Limit *int64 `json:"limit" jsonschema:"Maximum number of events"`
}

type GetUpcomingEventsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
