// Code generated by mcpidl. DO NOT EDIT.

package main

type SetAlarmInput struct {
	Hour    int64   `json:"hour" jsonschema:"Hour (0-23)"`
	Message *string `json:"message" jsonschema:"Alarm message/label"`
	Minute  int64   `json:"minute" jsonschema:"Minute (0-59)"`
}

type SetAlarmOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetNextAlarmTimeInput struct {
}

type GetNextAlarmTimeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type HasAlarmSetInput struct {
}

type HasAlarmSetOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type ShowAlarmsInput struct {
}

type ShowAlarmsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type StartTimerInput struct {
	Message *string `json:"message" jsonschema:"Timer message/label"`
	Seconds int64   `json:"seconds" jsonschema:"Timer duration in seconds"`
}

type StartTimerOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type ShowStopwatchInput struct {
}

type ShowStopwatchOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetSystemSummaryInput struct {
}

type GetSystemSummaryOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
