// Code generated by mcpidl. DO NOT EDIT.

package main

type AddContactInput struct {
	Email *string `json:"email" jsonschema:"Email address"`
	Name  string  `json:"name" jsonschema:"Contact name"`
	Phone string  `json:"phone" jsonschema:"Phone number"`
}

type AddContactOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetAllContactsInput struct {
	Limit *int64 `json:"limit" jsonschema:"Maximum number of contacts"`
}

type GetAllContactsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SearchContactsByNameInput struct {
	Name string `json:"name" jsonschema:"Name to search for"`
}

type SearchContactsByNameOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetContactByIdInput struct {
	ContactId string `json:"contactId" jsonschema:"Contact ID"`
}

type GetContactByIdOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type DeleteContactInput struct {
	ContactId string `json:"contactId" jsonschema:"Contact ID to delete"`
}

type DeleteContactOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type CallPhoneInput struct {
	PhoneNumber string `json:"phoneNumber" jsonschema:"Phone number to call"`
}

type CallPhoneOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type DialPhoneInput struct {
	PhoneNumber string `json:"phoneNumber" jsonschema:"Phone number to dial"`
}

type DialPhoneOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetContactCountInput struct {
}

type GetContactCountOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
