// Code generated by mcpidl. DO NOT EDIT.

package main

type TestStruct struct {
	Field1 string `json:"field1" jsonschema:"Field 1"`
	Field2 any    `json:"field2,omitempty" jsonschema:"Field 2 with any type"`
}

// GetField1 returns the value of Field1 field
func (s TestStruct) GetField1() string {
	return s.Field1
}

// GetField2 returns the value of Field2 field
func (s TestStruct) GetField2() any {
	return s.Field2
}

const TestDataFieldTool string = "test_data_field"

const TestDataFieldDescription string = "Test data field and any type"

type TestDataFieldInput struct {
	Data         map[string]any `json:"data" jsonschema:"Data object"`
	AnyField     any            `json:"any_field" jsonschema:"Any type field"`
	OptionalData map[string]any `json:"optional_data,omitempty" jsonschema:"Optional data object"`
	OptionalAny  any            `json:"optional_any,omitempty" jsonschema:"Optional any type field"`
}

// GetData returns the value of Data field
func (s TestDataFieldInput) GetData() map[string]any {
	return s.Data
}

// GetAnyField returns the value of AnyField field
func (s TestDataFieldInput) GetAnyField() any {
	return s.AnyField
}

// GetOptionalData returns the value of OptionalData field
func (s TestDataFieldInput) GetOptionalData() map[string]any {
	return s.OptionalData
}

// GetOptionalAny returns the value of OptionalAny field
func (s TestDataFieldInput) GetOptionalAny() any {
	return s.OptionalAny
}

type TestDataFieldOutput struct {
	Result   any              `json:"result" jsonschema:"Result with any type"`
	DataList []map[string]any `json:"data_list,omitempty" jsonschema:"List of data objects"`
	AnyList  []any            `json:"any_list,omitempty" jsonschema:"List of any types"`
}

// GetResult returns the value of Result field
func (s TestDataFieldOutput) GetResult() any {
	return s.Result
}

// GetDataList returns the value of DataList field
func (s TestDataFieldOutput) GetDataList() []map[string]any {
	return s.DataList
}

// GetAnyList returns the value of AnyList field
func (s TestDataFieldOutput) GetAnyList() []any {
	return s.AnyList
}
