// Code generated by mcpidl. DO NOT EDIT.

package main

type System struct {
	CurrApp  string `json:"curr_app" jsonschema:"当前app"`
	Version  string `json:"version" jsonschema:"版本号"`
	IsActive *bool  `json:"is_active" jsonschema:"是否激活"`
}

type UserInfo struct {
	UserId     string  `json:"user_id" jsonschema:"用户ID"`
	UserName   string  `json:"user_name" jsonschema:"用户名"`
	Email      *string `json:"email" jsonschema:"邮箱"`
	Phone      *string `json:"phone" jsonschema:"手机号"`
	SystemInfo System  `json:"system_info" jsonschema:"系统信息"`
}

const GetUserInfoTool string = "get_user_info"

const GetUserInfoDescription string = `Get user information`

const GetSystemInfoTool string = "get_system_info"

const GetSystemInfoDescription string = `Get user information`

type GetUserInfoInput struct {
	UserId string `json:"user_id" jsonschema:"User ID"`
}

type GetUserInfoOutput struct {
	Success      *bool    `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string  `json:"error_message" jsonschema:"Error message if operation failed"`
	UserInfo     UserInfo `json:"user_info" jsonschema:"User information"`
	SystemInfo   System   `json:"system_info" jsonschema:"System information"`
}

type GetSystemInfoInput struct {
	UserId string `json:"user_id" jsonschema:"User ID"`
}

type GetSystemInfoOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
	SystemInfo   System  `json:"system_info" jsonschema:"System information"`
}
