// Code generated by mcpidl. DO NOT EDIT.

package main

type GetAllDocumentsInput struct {
	Limit *int64 `json:"limit" jsonschema:"Maximum number of documents"`
}

type GetAllDocumentsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetDocumentCountInput struct {
}

type GetDocumentCountOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type CreateTextDocumentInput struct {
	Content  string `json:"content" jsonschema:"Document content"`
	Filename string `json:"filename" jsonschema:"Document filename"`
}

type CreateTextDocumentOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type ReadTextDocumentInput struct {
	DocumentId string `json:"documentId" jsonschema:"Document ID"`
}

type ReadTextDocumentOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type DeleteDocumentInput struct {
	DocumentId string `json:"documentId" jsonschema:"Document ID to delete"`
}

type DeleteDocumentOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SearchDocumentsInput struct {
	Keyword string `json:"keyword" jsonschema:"Search keyword"`
}

type SearchDocumentsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
