// Code generated by mcpidl. DO NOT EDIT.

package main

const TestEscapedQuotesTool string = "test_escaped_quotes"

const TestEscapedQuotesDescription string = "This is a tool with \"escaped quotes\" and unescaped quotes"

type TestEscapedQuotesInput struct {
	Field1 string  `json:"field1" jsonschema:"This field has \"escaped quotes\" and normal text"`
	Field2 *string `json:"field2,omitempty" jsonschema:"This field has unescaped \"quotes\" and \n newlines"`
	Field3 string  `json:"field3" jsonschema:"This field has \t tabs and \"escaped quotes\""`
}

// GetField1 returns the value of Field1 field
func (s TestEscapedQuotesInput) GetField1() string {
	return s.Field1
}

// GetField2 returns the value of Field2 field
func (s TestEscapedQuotesInput) GetField2() string {
	if s.Field2 == nil {
		var zero string
		return zero
	}
	return *s.Field2
}

// GetField3 returns the value of Field3 field
func (s TestEscapedQuotesInput) GetField3() string {
	return s.Field3
}

type TestEscapedQuotesOutput struct {
	Result *string `json:"result,omitempty" jsonschema:"Result with \"escaped quotes\""`
}

// GetResult returns the value of Result field
func (s TestEscapedQuotesOutput) GetResult() string {
	if s.Result == nil {
		var zero string
		return zero
	}
	return *s.Result
}
