// Code generated by mcpidl. DO NOT EDIT.

package main

const TestEscapedDescTool string = "test_escaped_desc"

const TestEscapedDescDescription string = "This description has \"double quotes\", \nnewlines, and \ttabs."

type TestEscapedDescInput struct {
	Field1 string `json:"field1" jsonschema:"Field 1"`
}

// GetField1 returns the value of Field1 field
func (s TestEscapedDescInput) GetField1() string {
	return s.Field1
}

type TestEscapedDescOutput struct {
	Result *bool `json:"result,omitempty" jsonschema:"Result"`
}

// GetResult returns the value of Result field
func (s TestEscapedDescOutput) GetResult() bool {
	if s.Result == nil {
		var zero bool
		return zero
	}
	return *s.Result
}
