// Code generated by mcpidl. DO NOT EDIT.

package main

type GetAllImagesInput struct {
	Limit *int64 `json:"limit" jsonschema:"Maximum number of images"`
}

type GetAllImagesOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetImageCountInput struct {
}

type GetImageCountOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SearchImagesInput struct {
	Keyword string `json:"keyword" jsonschema:"Search keyword"`
}

type SearchImagesOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type DeleteImageInput struct {
	ImageId string `json:"imageId" jsonschema:"Image ID to delete"`
}

type DeleteImageOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetAllVideosInput struct {
	Limit *int64 `json:"limit" jsonschema:"Maximum number of videos"`
}

type GetAllVideosOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetVideoCountInput struct {
}

type GetVideoCountOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SearchVideosInput struct {
	Keyword string `json:"keyword" jsonschema:"Search keyword"`
}

type SearchVideosOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type DeleteVideoInput struct {
	VideoId string `json:"videoId" jsonschema:"Video ID to delete"`
}

type DeleteVideoOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
