// Code generated by mcpidl. DO NOT EDIT.

package main

type TestData struct {
	FieldOne    string         `json:"field_one" jsonschema:"Field one"`
	FieldTwo    int64          `json:"field_two,omitempty" jsonschema:"Field two"`
	NestedData  map[string]any `json:"nested_data" jsonschema:"Nested data"`
	StringArray []string       `json:"string_array,omitempty" jsonschema:"String array"`
}

// GetFieldOne returns the value of FieldOne field
func (s TestData) GetFieldOne() string {
	return s.FieldOne
}

// GetFieldTwo returns the value of FieldTwo field
func (s TestData) GetFieldTwo() int64 {
	return s.FieldTwo
}

// GetNestedData returns the value of NestedData field
func (s TestData) GetNestedData() map[string]any {
	return s.NestedData
}

// GetStringArray returns the value of StringArray field
func (s TestData) GetStringArray() []string {
	return s.StringArray
}

const TestJsonTagTool string = "test_json_tag"

const TestJsonTagDescription string = "Test JSON tag generation"

type TestJsonTagInput struct {
	CurrentApp string `json:"current_app" jsonschema:"Current application name"`
	UserId     int64  `json:"user_id" jsonschema:"User ID"`
	IsActive   bool   `json:"is_active,omitempty" jsonschema:"Is active"`
	AppVersion string `json:"app_version,omitempty" jsonschema:"Application version"`
}

// GetCurrentApp returns the value of CurrentApp field
func (s TestJsonTagInput) GetCurrentApp() string {
	return s.CurrentApp
}

// GetUserId returns the value of UserId field
func (s TestJsonTagInput) GetUserId() int64 {
	return s.UserId
}

// GetIsActive returns the value of IsActive field
func (s TestJsonTagInput) GetIsActive() bool {
	return s.IsActive
}

// GetAppVersion returns the value of AppVersion field
func (s TestJsonTagInput) GetAppVersion() string {
	return s.AppVersion
}

type TestJsonTagOutput struct {
	ResultCode   int32          `json:"result_code" jsonschema:"Result code"`
	ErrorMessage string         `json:"error_message,omitempty" jsonschema:"Error message"`
	UserInfo     map[string]any `json:"user_info" jsonschema:"User information"`
	AppList      []string       `json:"app_list,omitempty" jsonschema:"Application list"`
}

// GetResultCode returns the value of ResultCode field
func (s TestJsonTagOutput) GetResultCode() int32 {
	return s.ResultCode
}

// GetErrorMessage returns the value of ErrorMessage field
func (s TestJsonTagOutput) GetErrorMessage() string {
	return s.ErrorMessage
}

// GetUserInfo returns the value of UserInfo field
func (s TestJsonTagOutput) GetUserInfo() map[string]any {
	return s.UserInfo
}

// GetAppList returns the value of AppList field
func (s TestJsonTagOutput) GetAppList() []string {
	return s.AppList
}
