// Code generated by mcpidl. DO NOT EDIT.

package main

const SnakeCaseTool string = "snake_case_tool"

const SnakeCaseToolDescription string = "Test snake case tool name"

const CamelCaseTool string = "camel_case_tool"

const CamelCaseToolDescription string = "Test camel case tool name"

type SnakeCaseToolInput struct {
	SnakeField string `json:"snake_field" jsonschema:"Snake case field"`
	CamelField string `json:"camel_field" jsonschema:"Camel case field"`
}

type SnakeCaseToolOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}

type CamelCaseToolInput struct {
	SnakeField string `json:"snake_field" jsonschema:"Snake case field"`
	CamelField string `json:"camel_field" jsonschema:"Camel case field"`
}

type CamelCaseToolOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}
