// Code generated by mcpidl. DO NOT EDIT.

package main

const CaptureScreenshotTool string = "capture_screenshot"

const CaptureScreenshotDescription string = `Capture a screenshot from the Android device and return it as an image.
  
  **Output:** Returns the screenshot as an image. The screenshot is automatically captured from the Android device via ADB, with the shortest side resized to 512px for efficient transmission. 
  
  **Notes:** 
   - A screenshot is automatically captured after the operation completes, with the shortest side resized to 512px.`

type CaptureScreenshotInput struct {
	DeviceId string `json:"device_id" jsonschema:"Device ID"`
}

type CaptureScreenshotOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
	Image        *string `json:"image" jsonschema:"Base64 encoded image"`
}
