// Code generated by mcpidl. DO NOT EDIT.

package main

const TestMultilineDescTool string = "test_multiline_desc"

const TestMultilineDescDescription string = "This is a multiline description. It contains multiple lines and \"quoted\" text. It also has special `characters` like \n and \t. This should be properly escaped when using double quotes."

type TestMultilineDescInput struct {
	Field1 string `json:"field1" jsonschema:"Field 1"`
}

// GetField1 returns the value of Field1 field
func (s TestMultilineDescInput) GetField1() string {
	return s.Field1
}

type TestMultilineDescOutput struct {
	Result *bool `json:"result,omitempty" jsonschema:"Result"`
}

// GetResult returns the value of Result field
func (s TestMultilineDescOutput) GetResult() bool {
	if s.Result == nil {
		var zero bool
		return zero
	}
	return *s.Result
}
