// Code generated by mcpidl. DO NOT EDIT.

package main

const TestOmitemptyTool string = "test_omitempty"

const TestOmitemptyDescription string = "Test omitempty functionality"

type TestOmitemptyInput struct {
	RequiredField string          `json:"required_field" jsonschema:"Required field"`
	OptionalField *string         `json:"optional_field,omitempty" jsonschema:"Optional field"`
	ArrayField    *[]string       `json:"array_field,omitempty" jsonschema:"Array field"`
	ObjectField   *map[string]any `json:"object_field,omitempty" jsonschema:"Object field"`
}

// GetRequiredField returns the value of RequiredField field
func (s TestOmitemptyInput) GetRequiredField() string {
	return s.RequiredField
}

// GetOptionalField returns the value of OptionalField field
func (s TestOmitemptyInput) GetOptionalField() string {
	if s.OptionalField == nil {
		var zero string
		return zero
	}
	return *s.OptionalField
}

// GetArrayField returns the value of ArrayField field
func (s TestOmitemptyInput) GetArrayField() []string {
	if s.ArrayField == nil {
		var zero []string
		return zero
	}
	return *s.ArrayField
}

// GetObjectField returns the value of ObjectField field
func (s TestOmitemptyInput) GetObjectField() map[string]any {
	if s.ObjectField == nil {
		var zero map[string]any
		return zero
	}
	return *s.ObjectField
}

type TestOmitemptyOutput struct {
	RequiredOutput string  `json:"required_output" jsonschema:"Required output field"`
	OptionalOutput *string `json:"optional_output,omitempty" jsonschema:"Optional output field"`
}

// GetRequiredOutput returns the value of RequiredOutput field
func (s TestOmitemptyOutput) GetRequiredOutput() string {
	return s.RequiredOutput
}

// GetOptionalOutput returns the value of OptionalOutput field
func (s TestOmitemptyOutput) GetOptionalOutput() string {
	if s.OptionalOutput == nil {
		var zero string
		return zero
	}
	return *s.OptionalOutput
}
