// Code generated by mcpidl. DO NOT EDIT.

package main

const LaunchTool string = "Launch"

const LaunchDescription string = "Launch an Android application by its app name"

const TapTool string = "Tap"

const TapDescription string = "Tap on a specific coordinate on the screen"

const SwipeTool string = "Swipe"

const SwipeDescription string = "Perform a swipe gesture from one coordinate to another"

const TypeTool string = "Type"

const TypeDescription string = "Type text into the currently focused input field"

const WaitTool string = "Wait"

const WaitDescription string = "Wait for a specified duration before proceeding (maximum 30 seconds)"

const LongpressTool string = "LongPress"

const LongpressDescription string = "Press and hold on a specific coordinate for a duration"

const DoubleclickTool string = "DoubleClick"

const DoubleclickDescription string = "Perform a double-click on a specific coordinate"

const HomeTool string = "Home"

const HomeDescription string = "Return to the home screen"

const BackTool string = "Back"

const BackDescription string = "Navigate back to the previous screen"

type LaunchInput struct {
	AppName string `json:"appName" jsonschema:"Application name"`
}

type LaunchOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type TapInput struct {
	Coordinate []string `json:"coordinate" jsonschema:"Tap coordinates [x, y]"`
	OriginSize []string `json:"originSize" jsonschema:"Original screen size [width, height]"`
	ScaledSize []string `json:"scaledSize" jsonschema:"Scaled screenshot size [width, height]"`
}

type TapOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SwipeInput struct {
	EndCoordinate   []string `json:"endCoordinate" jsonschema:"End coordinates [x, y]"`
	OriginSize      []string `json:"originSize" jsonschema:"Original screen size [width, height]"`
	ScaledSize      []string `json:"scaledSize" jsonschema:"Scaled screenshot size [width, height]"`
	StartCoordinate []string `json:"startCoordinate" jsonschema:"Start coordinates [x, y]"`
}

type SwipeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type TypeInput struct {
	Text string `json:"text" jsonschema:"Text content to type"`
}

type TypeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type WaitInput struct {
	Duration float64 `json:"duration" jsonschema:"Wait duration in seconds (maximum 30 seconds)"`
}

type WaitOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type LongpressInput struct {
	OriginSize []string `json:"originSize" jsonschema:"Original screen size [width, height]"`
	ScaledSize []string `json:"scaledSize" jsonschema:"Scaled screenshot size [width, height]"`
	Coordinate []string `json:"coordinate" jsonschema:"Long press coordinates [x, y]"`
	Duration   float64  `json:"duration" jsonschema:"Long press duration in seconds (maximum 10 seconds)"`
}

type LongpressOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type DoubleclickInput struct {
	Coordinate []string `json:"coordinate" jsonschema:"Double click coordinates [x, y]"`
	OriginSize []string `json:"originSize" jsonschema:"Original screen size [width, height]"`
	ScaledSize []string `json:"scaledSize" jsonschema:"Scaled screenshot size [width, height]"`
}

type DoubleclickOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type HomeInput struct {
}

type HomeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type BackInput struct {
}

type BackOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
