// Code generated by mcpidl. DO NOT EDIT.

package main

const LaunchTool string = "launch"

const LaunchDescription string = "Launch an Android application by its app name"

const TapTool string = "tap"

const TapDescription string = "Tap on a specific coordinate on the screen"

const SwipeTool string = "swipe"

const SwipeDescription string = "Perform a swipe gesture from one coordinate to another"

const TypeTool string = "type"

const TypeDescription string = "Type text into the currently focused input field"

const WaitTool string = "wait"

const WaitDescription string = "Wait for a specified duration before proceeding (maximum 30 seconds)"

const LongPressTool string = "long_press"

const LongPressDescription string = "Press and hold on a specific coordinate for a duration"

const DoubleClickTool string = "double_click"

const DoubleClickDescription string = "Perform a double-click on a specific coordinate"

const HomeTool string = "home"

const HomeDescription string = "Return to the home screen"

const BackTool string = "back"

const BackDescription string = "Navigate back to the previous screen"

type LaunchInput struct {
	AppName string `json:"app_name" jsonschema:"Application name"`
}

type LaunchOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}

type TapInput struct {
	Coordinate []string `json:"coordinate" jsonschema:"Tap coordinates [x, y]"`
	OriginSize []string `json:"origin_size" jsonschema:"Original screen size [width, height]"`
	ScaledSize []string `json:"scaled_size" jsonschema:"Scaled screenshot size [width, height]"`
}

type TapOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}

type SwipeInput struct {
	EndCoordinate   []string `json:"end_coordinate" jsonschema:"End coordinates [x, y]"`
	OriginSize      []string `json:"origin_size" jsonschema:"Original screen size [width, height]"`
	ScaledSize      []string `json:"scaled_size" jsonschema:"Scaled screenshot size [width, height]"`
	StartCoordinate []string `json:"start_coordinate" jsonschema:"Start coordinates [x, y]"`
}

type SwipeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}

type TypeInput struct {
	Text string `json:"text" jsonschema:"Text content to type"`
}

type TypeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}

type WaitInput struct {
	Duration float64 `json:"duration" jsonschema:"Wait duration in seconds (maximum 30 seconds)"`
}

type WaitOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}

type LongPressInput struct {
	OriginSize []string `json:"origin_size" jsonschema:"Original screen size [width, height]"`
	ScaledSize []string `json:"scaled_size" jsonschema:"Scaled screenshot size [width, height]"`
	Coordinate []string `json:"coordinate" jsonschema:"Long press coordinates [x, y]"`
	Duration   float64  `json:"duration" jsonschema:"Long press duration in seconds (maximum 10 seconds)"`
}

type LongPressOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}

type DoubleClickInput struct {
	Coordinate []string `json:"coordinate" jsonschema:"Double click coordinates [x, y]"`
	OriginSize []string `json:"origin_size" jsonschema:"Original screen size [width, height]"`
	ScaledSize []string `json:"scaled_size" jsonschema:"Scaled screenshot size [width, height]"`
}

type DoubleClickOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}

type HomeInput struct {
}

type HomeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}

type BackInput struct {
}

type BackOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"error_message" jsonschema:"Error message if operation failed"`
}
