// Code generated by mcpidl. DO NOT EDIT.

package main

type GetSystemBrightnessInput struct {
}

type GetSystemBrightnessOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SetSystemBrightnessInput struct {
	Brightness int64 `json:"brightness" jsonschema:"Brightness level (0-255)"`
}

type SetSystemBrightnessOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetBrightnessModeInput struct {
}

type GetBrightnessModeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SetBrightnessModeInput struct {
	Auto bool `json:"auto" jsonschema:"Whether to enable auto brightness"`
}

type SetBrightnessModeOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetSystemAutoRotateInput struct {
}

type GetSystemAutoRotateOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SetSystemAutoRotateInput struct {
	Enabled bool `json:"enabled" jsonschema:"Whether to enable auto-rotate"`
}

type SetSystemAutoRotateOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetScreenTimeoutInput struct {
}

type GetScreenTimeoutOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SetScreenTimeoutInput struct {
	TimeoutMs int64 `json:"timeoutMs" jsonschema:"Timeout in milliseconds"`
}

type SetScreenTimeoutOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
