// Code generated by mcpidl. DO NOT EDIT.

package main

type SendSmsInput struct {
	Message     string `json:"message" jsonschema:"Message content"`
	PhoneNumber string `json:"phoneNumber" jsonschema:"Recipient phone number"`
}

type SendSmsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetAllSmsInput struct {
	Limit *int64 `json:"limit" jsonschema:"Maximum number of messages"`
}

type GetAllSmsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetInboxSmsInput struct {
	Limit *int64 `json:"limit" jsonschema:"Maximum number of messages"`
}

type GetInboxSmsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetSentSmsInput struct {
	Limit *int64 `json:"limit" jsonschema:"Maximum number of messages"`
}

type GetSentSmsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetSmsCountInput struct {
}

type GetSmsCountOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type DeleteSmsInput struct {
	SmsId string `json:"smsId" jsonschema:"SMS message ID to delete"`
}

type DeleteSmsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SearchSmsInput struct {
	Keyword string `json:"keyword" jsonschema:"Search keyword"`
	Limit   *int64 `json:"limit" jsonschema:"Maximum number of results"`
}

type SearchSmsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
