// Code generated by mcpidl. DO NOT EDIT.

package main

type SnakeCaseToolInput struct {
	TestField string `json:"testField" jsonschema:"Test field"`
}

type SnakeCaseToolOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
