// Code generated by mcpidl. DO NOT EDIT.

package main

type IsWifiEnabledInput struct {
}

type IsWifiEnabledOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type SetWifiEnabledInput struct {
	Enabled bool `json:"enabled" jsonschema:"Whether to enable WiFi"`
}

type SetWifiEnabledOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetCurrentWifiInfoInput struct {
}

type GetCurrentWifiInfoOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type GetScanResultsInput struct {
}

type GetScanResultsOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}

type StartScanInput struct {
}

type StartScanOutput struct {
	Success      *bool   `json:"success" jsonschema:"Whether the operation succeeded"`
	ErrorMessage *string `json:"errorMessage" jsonschema:"Error message if operation failed"`
}
